
start_urls_apartments = [
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_repairs%5D%5B1%5D=3&search%5Bfilter_enum_repairs%5D%5B2%5D=6&search%5Bfilter_enum_repairs%5D%5B3%5D=4&search%5Bfilter_enum_repairs%5D%5B4%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=1&search%5Bfilter_float_floor:to%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=6&search%5Bfilter_float_floor:to%5D=16&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=1&search%5Bfilter_float_floor:to%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=6&search%5Bfilter_float_floor:to%5D=16&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=1&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_float_floor:to%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=1&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_float_floor:from%5D=6&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_float_floor:to%5D=6&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=7&search%5Bfilter_float_floor:to%5D=8&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=9&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_float_floor:to%5D=6&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=7&search%5Bfilter_float_floor:to%5D=8&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=9&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_float_floor:to%5D=6&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_float_floor:from%5D=7&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_repairs%5D%5B1%5D=3&search%5Bfilter_enum_repairs%5D%5B2%5D=4&search%5Bfilter_enum_repairs%5D%5B3%5D=5&search%5Bfilter_enum_repairs%5D%5B4%5D=6&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=4&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=4&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_float_floor:to%5D=8&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=9&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:to%5D=6&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=7&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=6&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=6&search%5Bfilter_enum_type_of_market%5D%5B0%5D=primary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_repairs%5D%5B1%5D=4&search%5Bfilter_enum_repairs%5D%5B2%5D=5&search%5Bfilter_enum_repairs%5D%5B3%5D=6&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=4&search%5Bfilter_enum_repairs%5D%5B1%5D=5&search%5Bfilter_enum_repairs%5D%5B2%5D=6&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_float_floor:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_float_floor:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:to%5D=1&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=2&search%5Bfilter_float_floor:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_total_area:to%5D=50&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_total_area:from%5D=55&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=4&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=4&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=4&search%5Bfilter_float_floor:to%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=6&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=yes&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_repairs%5D%5B1%5D=4&search%5Bfilter_enum_repairs%5D%5B2%5D=5&search%5Bfilter_enum_repairs%5D%5B3%5D=6&search%5Bfilter_enum_repairs%5D%5B4%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=1&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=6&search%5Bfilter_enum_repairs%5D%5B1%5D=5&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=2&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_float_floor:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_float_floor:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:to%5D=1&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=2&search%5Bfilter_float_floor:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=4&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=3&search%5Bfilter_float_floor:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_floor:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=3&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=4&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=4&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=4&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary',
    'https://www.olx.uz/nedvizhimost/kvartiry/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_enum_furnished%5D%5B0%5D=no&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_repairs%5D%5B0%5D=4&search%5Bfilter_enum_type_of_market%5D%5B0%5D=secondary'
]




start_urls_houses = [
    # 'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_enum_private_house_type%5D%5B0%5D=2&search%5Bfilter_enum_private_house_type%5D%5B1%5D=3&search%5Bfilter_enum_private_house_type%5D%5B2%5D=5&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    # 'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_enum_private_house_type%5D%5B0%5D=6&search%5Bfilter_enum_private_house_type%5D%5B1%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    # 'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',





    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:to%5D=150&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_enum_private_house_type%5D%5B0%5D=6&search%5Bfilter_enum_private_house_type%5D%5B1%5D=5&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_enum_private_house_type%5D%5B0%5D=4&search%5Bfilter_enum_private_house_type%5D%5B1%5D=2&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_private_house_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_enum_private_house_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_float_total_area:to%5D=125&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_float_total_area:from%5D=150&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:to%5D=80&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=90&search%5Bfilter_float_total_area:to%5D=150&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes&search%5Bfilter_enum_location%5D%5B0%5D=2&search%5Bfilter_enum_location%5D%5B1%5D=3&search%5Bfilter_enum_location%5D%5B2%5D=4&search%5Bfilter_enum_location%5D%5B3%5D=5&search%5Bfilter_enum_location%5D%5B4%5D=6&search%5Bfilter_enum_location%5D%5B5%5D=7&search%5Bfilter_enum_location%5D%5B6%5D=8',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_float_total_floors:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes&search%5Bfilter_enum_location%5D%5B0%5D=2&search%5Bfilter_enum_location%5D%5B1%5D=3&search%5Bfilter_enum_location%5D%5B2%5D=4&search%5Bfilter_enum_location%5D%5B3%5D=5&search%5Bfilter_enum_location%5D%5B4%5D=7&search%5Bfilter_enum_location%5D%5B5%5D=8&search%5Bfilter_enum_location%5D%5B6%5D=6',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_float_total_floors:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_float_total_floors:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=3&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=yes',


    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_enum_private_house_type%5D%5B0%5D=6&search%5Bfilter_enum_private_house_type%5D%5B1%5D=5&search%5Bfilter_enum_private_house_type%5D%5B2%5D=4&search%5Bfilter_enum_private_house_type%5D%5B3%5D=2&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_enum_private_house_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:to%5D=150&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=yes&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_enum_private_house_type%5D%5B0%5D=6&search%5Bfilter_enum_private_house_type%5D%5B1%5D=2&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_enum_private_house_type%5D%5B0%5D=5&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_private_house_type%5D%5B0%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_private_house_type%5D%5B0%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_enum_private_house_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_enum_private_house_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:to%5D=150&search%5Bfilter_enum_private_house_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=3&search%5Bfilter_enum_private_house_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=2&search%5Bfilter_float_number_of_rooms:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_total_area:to%5D=90&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=3&search%5Bfilter_float_number_of_rooms:to%5D=3&search%5Bfilter_float_total_area:from%5D=100&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',


    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_float_total_area:to%5D=90&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_float_total_area:from%5D=100&search%5Bfilter_float_total_area:to%5D=150&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=4&search%5Bfilter_float_number_of_rooms:to%5D=4&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:to%5D=20&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=8&search%5Bfilter_enum_location%5D%5B1%5D=7&search%5Bfilter_enum_location%5D%5B2%5D=6&search%5Bfilter_enum_location%5D%5B3%5D=5&search%5Bfilter_enum_location%5D%5B4%5D=4&search%5Bfilter_enum_location%5D%5B5%5D=3&search%5Bfilter_enum_location%5D%5B6%5D=2',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:to%5D=20&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:to%5D=20&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=25&search%5Bfilter_float_total_area:to%5D=150&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=8&search%5Bfilter_enum_location%5D%5B1%5D=6&search%5Bfilter_enum_location%5D%5B2%5D=7&search%5Bfilter_enum_location%5D%5B3%5D=5&search%5Bfilter_enum_location%5D%5B4%5D=4&search%5Bfilter_enum_location%5D%5B5%5D=3',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=2',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:to%5D=1&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_float_total_floors:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=8&search%5Bfilter_enum_location%5D%5B1%5D=7&search%5Bfilter_enum_location%5D%5B2%5D=6&search%5Bfilter_enum_location%5D%5B3%5D=5&search%5Bfilter_enum_location%5D%5B4%5D=4&search%5Bfilter_enum_location%5D%5B5%5D=3&search%5Bfilter_enum_location%5D%5B6%5D=2',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_float_total_floors:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=2&search%5Bfilter_float_total_floors:to%5D=2&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=3&search%5Bfilter_float_total_floors:to%5D=3&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=7&search%5Bfilter_enum_location%5D%5B1%5D=8&search%5Bfilter_enum_location%5D%5B2%5D=5&search%5Bfilter_enum_location%5D%5B3%5D=6&search%5Bfilter_enum_location%5D%5B4%5D=4&search%5Bfilter_enum_location%5D%5B5%5D=3&search%5Bfilter_enum_location%5D%5B6%5D=2',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=3&search%5Bfilter_float_total_floors:to%5D=3&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=3&search%5Bfilter_float_total_floors:to%5D=3&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no&search%5Bfilter_enum_location%5D%5B0%5D=1',
    'https://www.olx.uz/nedvizhimost/doma/prodazha/?currency=UZS&search%5Border%5D=relevance:desc&search%5Bfilter_float_number_of_rooms:from%5D=5&search%5Bfilter_float_total_area:from%5D=175&search%5Bfilter_float_total_floors:from%5D=4&search%5Bfilter_enum_private_house_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_furnished_house%5D%5B0%5D=no'
]

start_urls_cars = [
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_fuel_type%5D%5B0%5D=547&search%5Bfilter_enum_fuel_type%5D%5B1%5D=543&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=cabriolet&search%5Bfilter_enum_car_body%5D%5B1%5D=pickup&search%5Bfilter_enum_car_body%5D%5B2%5D=coupe&search%5Bfilter_enum_car_body%5D%5B3%5D=estate-car&search%5Bfilter_enum_car_body%5D%5B4%5D=hatchback&search%5Bfilter_enum_car_body%5D%5B5%5D=minibus&search%5Bfilter_enum_fuel_type%5D%5B0%5D=546&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=off-road-vehicle&search%5Bfilter_enum_fuel_type%5D%5B0%5D=546&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=other&search%5Bfilter_enum_fuel_type%5D%5B0%5D=546&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_fuel_type%5D%5B0%5D=546&search%5Bfilter_enum_condition%5D%5B0%5D=perfect&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_fuel_type%5D%5B0%5D=546&search%5Bfilter_enum_condition%5D%5B0%5D=good&search%5Bfilter_enum_condition%5D%5B1%5D=mediocre&search%5Bfilter_enum_condition%5D%5B2%5D=needs_repairs&search%5Bfilter_enum_condition%5D%5B3%5D=new&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=cabriolet&search%5Bfilter_enum_car_body%5D%5B1%5D=coupe&search%5Bfilter_enum_car_body%5D%5B2%5D=pickup&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=minibus&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=off-road-vehicle&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=estate-car&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=estate-car&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_color%5D%5B1%5D=7&search%5Bfilter_enum_color%5D%5B2%5D=8&search%5Bfilter_enum_color%5D%5B3%5D=23&search%5Bfilter_enum_color%5D%5B4%5D=9&search%5Bfilter_enum_color%5D%5B5%5D=14&search%5Bfilter_enum_color%5D%5B6%5D=17&search%5Bfilter_enum_color%5D%5B7%5D=18&search%5Bfilter_enum_color%5D%5B8%5D=10&search%5Bfilter_enum_color%5D%5B9%5D=11&search%5Bfilter_enum_color%5D%5B10%5D=15&search%5Bfilter_enum_color%5D%5B11%5D=22&search%5Bfilter_enum_color%5D%5B12%5D=21&search%5Bfilter_enum_color%5D%5B13%5D=12&search%5Bfilter_enum_color%5D%5B14%5D=13&search%5Bfilter_enum_color%5D%5B15%5D=3&search%5Bfilter_enum_color%5D%5B16%5D=4&search%5Bfilter_enum_color%5D%5B17%5D=5&search%5Bfilter_enum_color%5D%5B18%5D=6&search%5Bfilter_enum_color%5D%5B19%5D=19&search%5Bfilter_enum_color%5D%5B20%5D=20&search%5Bfilter_enum_color%5D%5B21%5D=25&search%5Bfilter_enum_color%5D%5B22%5D=24&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=hatchback&search%5Bfilter_float_motor_mileage:to%5D=225000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=hatchback&search%5Bfilter_float_motor_mileage:from%5D=250000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=hatchback&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_color%5D%5B1%5D=3&search%5Bfilter_enum_color%5D%5B2%5D=4&search%5Bfilter_enum_color%5D%5B3%5D=5&search%5Bfilter_enum_color%5D%5B4%5D=6&search%5Bfilter_enum_color%5D%5B5%5D=7&search%5Bfilter_enum_color%5D%5B6%5D=8&search%5Bfilter_enum_color%5D%5B7%5D=9&search%5Bfilter_enum_color%5D%5B8%5D=10&search%5Bfilter_enum_color%5D%5B9%5D=11&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=hatchback&search%5Bfilter_enum_color%5D%5B0%5D=12&search%5Bfilter_enum_color%5D%5B1%5D=13&search%5Bfilter_enum_color%5D%5B2%5D=14&search%5Bfilter_enum_color%5D%5B3%5D=15&search%5Bfilter_enum_color%5D%5B4%5D=17&search%5Bfilter_enum_color%5D%5B5%5D=18&search%5Bfilter_enum_color%5D%5B6%5D=19&search%5Bfilter_enum_color%5D%5B7%5D=20&search%5Bfilter_enum_color%5D%5B8%5D=21&search%5Bfilter_enum_color%5D%5B9%5D=22&search%5Bfilter_enum_color%5D%5B10%5D=23&search%5Bfilter_enum_color%5D%5B11%5D=24&search%5Bfilter_enum_color%5D%5B12%5D=25&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',



    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:to%5D=30000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:from%5D=50000&search%5Bfilter_float_motor_mileage:to%5D=100000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:from%5D=125000&search%5Bfilter_float_motor_mileage:to%5D=200000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:from%5D=225000&search%5Bfilter_float_motor_mileage:to%5D=300000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:from%5D=300000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',


    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_color%5D%5B0%5D=3&search%5Bfilter_enum_color%5D%5B1%5D=4&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_color%5D%5B0%5D=5&search%5Bfilter_enum_color%5D%5B1%5D=6&search%5Bfilter_enum_color%5D%5B2%5D=7&search%5Bfilter_enum_color%5D%5B3%5D=8&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_color%5D%5B0%5D=9&search%5Bfilter_enum_color%5D%5B1%5D=12&search%5Bfilter_enum_color%5D%5B2%5D=10&search%5Bfilter_enum_color%5D%5B3%5D=11&search%5Bfilter_enum_color%5D%5B4%5D=13&search%5Bfilter_enum_color%5D%5B5%5D=14&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_color%5D%5B0%5D=15&search%5Bfilter_enum_color%5D%5B1%5D=17&search%5Bfilter_enum_color%5D%5B2%5D=19&search%5Bfilter_enum_color%5D%5B3%5D=18&search%5Bfilter_enum_color%5D%5B4%5D=20&search%5Bfilter_enum_color%5D%5B5%5D=21&search%5Bfilter_enum_color%5D%5B6%5D=24&search%5Bfilter_enum_color%5D%5B7%5D=22&search%5Bfilter_enum_color%5D%5B8%5D=23&search%5Bfilter_enum_color%5D%5B9%5D=25&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=other&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=other&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_color%5D%5B1%5D=12&search%5Bfilter_enum_color%5D%5B2%5D=13&search%5Bfilter_enum_color%5D%5B3%5D=14&search%5Bfilter_enum_color%5D%5B4%5D=15&search%5Bfilter_enum_color%5D%5B5%5D=3&search%5Bfilter_enum_color%5D%5B6%5D=4&search%5Bfilter_enum_color%5D%5B7%5D=5&search%5Bfilter_enum_color%5D%5B8%5D=6&search%5Bfilter_enum_color%5D%5B9%5D=7&search%5Bfilter_enum_color%5D%5B10%5D=18&search%5Bfilter_enum_color%5D%5B11%5D=8&search%5Bfilter_enum_color%5D%5B12%5D=9&search%5Bfilter_enum_color%5D%5B13%5D=10&search%5Bfilter_enum_color%5D%5B14%5D=11&search%5Bfilter_enum_color%5D%5B15%5D=17&search%5Bfilter_enum_color%5D%5B16%5D=19&search%5Bfilter_enum_color%5D%5B17%5D=20&search%5Bfilter_enum_color%5D%5B18%5D=21&search%5Bfilter_enum_color%5D%5B19%5D=22&search%5Bfilter_enum_color%5D%5B20%5D=23&search%5Bfilter_enum_color%5D%5B21%5D=25&search%5Bfilter_enum_color%5D%5B22%5D=24&search%5Bfilter_enum_fuel_type%5D%5B0%5D=545&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=cabriolet&search%5Bfilter_enum_car_body%5D%5B1%5D=pickup&search%5Bfilter_enum_car_body%5D%5B2%5D=estate-car&search%5Bfilter_enum_car_body%5D%5B3%5D=coupe&search%5Bfilter_enum_car_body%5D%5B4%5D=hatchback&search%5Bfilter_enum_car_body%5D%5B5%5D=minibus&search%5Bfilter_enum_car_body%5D%5B6%5D=sedan&search%5Bfilter_enum_fuel_type%5D%5B0%5D=544&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=off-road-vehicle&search%5Bfilter_enum_fuel_type%5D%5B0%5D=544&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=other&search%5Bfilter_enum_fuel_type%5D%5B0%5D=544&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',



    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=cabriolet&search%5Bfilter_enum_car_body%5D%5B1%5D=pickup&search%5Bfilter_enum_car_body%5D%5B2%5D=coupe&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=estate-car&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=minibus&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=hatchback&search%5Bfilter_float_motor_mileage:to%5D=125000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=hatchback&search%5Bfilter_float_motor_mileage:from%5D=125000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=hatchback&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_color%5D%5B1%5D=3&search%5Bfilter_enum_color%5D%5B2%5D=4&search%5Bfilter_enum_color%5D%5B3%5D=5&search%5Bfilter_enum_color%5D%5B4%5D=6&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=hatchback&search%5Bfilter_enum_color%5D%5B0%5D=7&search%5Bfilter_enum_color%5D%5B1%5D=14&search%5Bfilter_enum_color%5D%5B2%5D=15&search%5Bfilter_enum_color%5D%5B3%5D=17&search%5Bfilter_enum_color%5D%5B4%5D=23&search%5Bfilter_enum_color%5D%5B5%5D=18&search%5Bfilter_enum_color%5D%5B6%5D=19&search%5Bfilter_enum_color%5D%5B7%5D=20&search%5Bfilter_enum_color%5D%5B8%5D=8&search%5Bfilter_enum_color%5D%5B9%5D=9&search%5Bfilter_enum_color%5D%5B10%5D=10&search%5Bfilter_enum_color%5D%5B11%5D=11&search%5Bfilter_enum_color%5D%5B12%5D=12&search%5Bfilter_enum_color%5D%5B13%5D=13&search%5Bfilter_enum_color%5D%5B14%5D=21&search%5Bfilter_enum_color%5D%5B15%5D=22&search%5Bfilter_enum_color%5D%5B16%5D=24&search%5Bfilter_enum_color%5D%5B17%5D=25&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=off-road-vehicle&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_color%5D%5B1%5D=3&search%5Bfilter_enum_color%5D%5B2%5D=4&search%5Bfilter_enum_color%5D%5B3%5D=5&search%5Bfilter_enum_color%5D%5B4%5D=6&search%5Bfilter_enum_color%5D%5B5%5D=7&search%5Bfilter_enum_color%5D%5B6%5D=8&search%5Bfilter_enum_color%5D%5B7%5D=9&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=off-road-vehicle&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_color%5D%5B1%5D=20&search%5Bfilter_enum_color%5D%5B2%5D=21&search%5Bfilter_enum_color%5D%5B3%5D=22&search%5Bfilter_enum_color%5D%5B4%5D=10&search%5Bfilter_enum_color%5D%5B5%5D=11&search%5Bfilter_enum_color%5D%5B6%5D=12&search%5Bfilter_enum_color%5D%5B7%5D=13&search%5Bfilter_enum_color%5D%5B8%5D=14&search%5Bfilter_enum_color%5D%5B9%5D=15&search%5Bfilter_enum_color%5D%5B10%5D=17&search%5Bfilter_enum_color%5D%5B11%5D=18&search%5Bfilter_enum_color%5D%5B12%5D=19&search%5Bfilter_enum_color%5D%5B13%5D=23&search%5Bfilter_enum_color%5D%5B14%5D=24&search%5Bfilter_enum_color%5D%5B15%5D=25&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:to%5D=10000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',



    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:to%5D=10000&search%5Bfilter_enum_transmission_type%5D%5B0%5D=546&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:to%5D=10000&search%5Bfilter_enum_transmission_type%5D%5B0%5D=547&search%5Bfilter_enum_transmission_type%5D%5B1%5D=545&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:from%5D=20000&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:from%5D=20000&search%5Bfilter_enum_transmission_type%5D%5B0%5D=546&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:from%5D=20000&search%5Bfilter_enum_transmission_type%5D%5B0%5D=545&search%5Bfilter_enum_transmission_type%5D%5B1%5D=547&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:to%5D=30000&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_float_motor_mileage:from%5D=50000&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_color%5D%5B0%5D=3&search%5Bfilter_enum_color%5D%5B1%5D=4&search%5Bfilter_enum_color%5D%5B2%5D=7&search%5Bfilter_enum_color%5D%5B3%5D=8&search%5Bfilter_enum_color%5D%5B4%5D=5&search%5Bfilter_enum_color%5D%5B5%5D=6&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_color%5D%5B0%5D=9&search%5Bfilter_enum_color%5D%5B1%5D=10&search%5Bfilter_enum_color%5D%5B2%5D=11&search%5Bfilter_enum_color%5D%5B3%5D=12&search%5Bfilter_enum_color%5D%5B4%5D=13&search%5Bfilter_enum_color%5D%5B5%5D=14&search%5Bfilter_enum_color%5D%5B6%5D=15&search%5Bfilter_enum_color%5D%5B7%5D=17&search%5Bfilter_enum_color%5D%5B8%5D=18&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=sedan&search%5Bfilter_enum_color%5D%5B0%5D=19&search%5Bfilter_enum_color%5D%5B1%5D=21&search%5Bfilter_enum_color%5D%5B2%5D=20&search%5Bfilter_enum_color%5D%5B3%5D=22&search%5Bfilter_enum_color%5D%5B4%5D=23&search%5Bfilter_enum_color%5D%5B5%5D=24&search%5Bfilter_enum_color%5D%5B6%5D=25&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=other&search%5Bfilter_enum_color%5D%5B0%5D=1&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish',
    'https://www.olx.uz/transport/legkovye-avtomobili/?currency=UZS&search%5Bfilter_enum_car_body%5D%5B0%5D=other&search%5Bfilter_enum_color%5D%5B0%5D=2&search%5Bfilter_enum_color%5D%5B1%5D=7&search%5Bfilter_enum_color%5D%5B2%5D=8&search%5Bfilter_enum_color%5D%5B3%5D=9&search%5Bfilter_enum_color%5D%5B4%5D=10&search%5Bfilter_enum_color%5D%5B5%5D=11&search%5Bfilter_enum_color%5D%5B6%5D=19&search%5Bfilter_enum_color%5D%5B7%5D=12&search%5Bfilter_enum_color%5D%5B8%5D=13&search%5Bfilter_enum_color%5D%5B9%5D=14&search%5Bfilter_enum_color%5D%5B10%5D=22&search%5Bfilter_enum_color%5D%5B11%5D=15&search%5Bfilter_enum_color%5D%5B12%5D=23&search%5Bfilter_enum_color%5D%5B13%5D=24&search%5Bfilter_enum_color%5D%5B14%5D=17&search%5Bfilter_enum_color%5D%5B15%5D=3&search%5Bfilter_enum_color%5D%5B16%5D=6&search%5Bfilter_enum_color%5D%5B17%5D=4&search%5Bfilter_enum_color%5D%5B18%5D=5&search%5Bfilter_enum_color%5D%5B19%5D=18&search%5Bfilter_enum_color%5D%5B20%5D=20&search%5Bfilter_enum_color%5D%5B21%5D=21&search%5Bfilter_enum_color%5D%5B22%5D=25&search%5Bfilter_enum_fuel_type%5D%5B0%5D=542&search%5Bfilter_enum_terms_of_sale%5D%5B0%5D=oddiy_sotish'
]




start_urls_commercial_premises =[
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=1&search%5Bfilter_enum_premise_type%5D%5B1%5D=2&search%5Bfilter_enum_premise_type%5D%5B2%5D=3&search%5Bfilter_enum_premise_type%5D%5B3%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=5&search%5Bfilter_enum_premise_type%5D%5B1%5D=7&search%5Bfilter_enum_premise_type%5D%5B2%5D=6&search%5Bfilter_enum_premise_type%5D%5B3%5D=8&search%5Bfilter_enum_premise_type%5D%5B4%5D=9&search%5Bfilter_enum_premise_type%5D%5B5%5D=10&search%5Bfilter_enum_comission%5D%5B0%5D=yes',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=12&search%5Bfilter_enum_premise_type%5D%5B1%5D=11&search%5Bfilter_enum_comission%5D%5B0%5D=yes',


    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=60',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=70&search%5Bfilter_float_total_area:to%5D=90',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=100&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=1&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&page=15&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=1&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=2&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=70',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=2&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=80&search%5Bfilter_float_total_area:to%5D=100',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=2&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=125&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=2&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&page=19&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=2&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=2&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=90',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=100&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&page=24&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=3&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=3&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=70',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=80&search%5Bfilter_float_total_area:to%5D=100',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=125&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=4&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',



    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&page=14&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=4&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=5&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=5&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=5&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&page=25&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=5&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=6&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=6&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=6&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&page=23&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=6&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=7&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=8&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=8&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=8&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=9&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=9&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=9&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_premise_type%5D%5B0%5D=10&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=11&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=11&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=11&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=175',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=private&search%5Bfilter_enum_premise_type%5D%5B0%5D=12&search%5Bfilter_enum_comission%5D%5B0%5D=no',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=12&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:to%5D=90',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bprivate_business%5D=business&search%5Bfilter_enum_premise_type%5D%5B0%5D=12&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_float_total_area:from%5D=100&search%5Bfilter_float_total_area:to%5D=150',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&page=16&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=12&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',
    'https://www.olx.uz/nedvizhimost/kommercheskie-pomeshcheniya/prodazha/?currency=UZS&search%5Bfilter_enum_comission%5D%5B0%5D=no&search%5Bfilter_enum_premise_type%5D%5B0%5D=12&search%5Bfilter_float_total_area%3Afrom%5D=175&search%5Bprivate_business%5D=business',


]


import json

with open('olx_uz/olx_uz_apartments.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(len(data))  # Количество загруженных элементов
print(data[:5])  # Первые 5 записей


















