import scrapy


class LandItem(scrapy.Item):
    """OLX.uz listing item — common metadata fields."""

    # --- OLX common fields (present in all categories) ---
    title = scrapy.Field()
    price = scrapy.Field()
    currency = scrapy.Field()
    description = scrapy.Field()
    content_id = scrapy.Field()
    category = scrapy.Field()
    category_type = scrapy.Field()
    url = scrapy.Field()
    isBusiness = scrapy.Field()
    isHighlighted = scrapy.Field()
    isPromoted = scrapy.Field()
    promotion = scrapy.Field()
    delivery = scrapy.Field()
    createdTime = scrapy.Field()
    lastRefreshTime = scrapy.Field()
    pushupTime = scrapy.Field()
    validToTime = scrapy.Field()
    isActive = scrapy.Field()
    status = scrapy.Field()
    itemCondition = scrapy.Field()
    negotiable = scrapy.Field()
    cityName = scrapy.Field()
    regionName = scrapy.Field()
    districtName = scrapy.Field()
    user = scrapy.Field()

    # --- Land specific fields ---
    purpose = scrapy.Field()
    land_type = scrapy.Field()
    plot = scrapy.Field()
    total_area = scrapy.Field()
    in_city = scrapy.Field()
    location = scrapy.Field()
    water = scrapy.Field()
    gas = scrapy.Field()
    electricity = scrapy.Field()
    heating = scrapy.Field()
    canalization = scrapy.Field()
    internet = scrapy.Field()
    communications = scrapy.Field()
    near_is = scrapy.Field()
    phone = scrapy.Field()
    comission = scrapy.Field()
